version: 3

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_JMX_PORT=9093
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9093
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms256M
      - KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/etc/kafka/log4j.properties
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_BALANCER_ENABLE=true
      - KAFKA_CONFLUENT_BALANCER_CONSUMER_ENABLE=true
      - KAFKA_CONFLUENT_BALANCER_TOPIC_ENABLE=true
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_LOG_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_METRICS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_COMMAND_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_REPLICATION_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_TRANSACTION_STATE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_CONNECT_STATUS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_CONNECT_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_CONNECT_CONFIGS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - KAFKA_CONFLUENT_CONNECT_GROUP_ID="connect-cluster"
      - KAFKA_CONFLUENT_CONNECT_CONFIG_STORAGE_TOPIC="connect-configs"
      - KAFKA_CONFLUENT_CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets"
      - KAFKA_CONFLUENT_CONNECT_STATUS_STORAGE_TOPIC="connect-status"
      - KAFKA_CONFLUENT_CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
      - KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS="localhost:9092"
      - KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT="localhost:2181"
      - KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS="1"
      - KAFKA_CONFLUENT_METRICS_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID="anonymous"
      - KAFKA_CONFLUENT_SUPPORT_CLUSTER_ID="anonymous"
      - KAFKA_CONFLUENT_SUPPORT_TOPIC_REPLICAS="1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_INTERVAL_MS="60000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_REPLICATION_FACTOR="1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_PARTITIONS="1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_RETENTION_MS="604800000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_CLEANUP_POLICY="delete"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_SEGMENT_BYTES="104857600"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_COMPACTION="false"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_COMPACTION_LAG_MS="0"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_INDEX_INTERVAL_BYTES="4096"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_DELETE_RETENTION_MS="86400000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_FILE_DELETE_DELAY_MS="60000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_INSYNC_REPLICAS="1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_SEGMENT_MS="604800000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_RETENTION_BYTES="-1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MAX_MESSAGE_BYTES="1000012"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_UNCLEAN_LEADER_ELECTION_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_PREALLOCATE="false"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_TIMESTAMP_TYPE="CreateTime"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS="9223372036854775807"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_DOWNCONVERSION_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_CLEANABLE_DIRTY_RATIO="0.5"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_COMPACTION_LAG_MS="0"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_SEGMENT_BYTES="104857600"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_COMPACTION="false"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_INDEX_INTERVAL_BYTES="4096"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_DELETE_RETENTION_MS="86400000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_FILE_DELETE_DELAY_MS="60000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_INSYNC_REPLICAS="1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_SEGMENT_MS="604800000"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_RETENTION_BYTES="-1"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MAX_MESSAGE_BYTES="1000012"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_UNCLEAN_LEADER_ELECTION_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_PREALLOCATE="false"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_TIMESTAMP_TYPE="CreateTime"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS="9223372036854775807"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MESSAGE_DOWNCONVERSION_ENABLE="true"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_MIN_CLEANABLE_DIRTY_RATIO="0.5"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_SEGMENT_BYTES="104857600"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_COMPACTION="false"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_INDEX_INTERVAL_BYTES="4096"
      - KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC_DELETE_RETENTION_MS="86400000"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_TICK_TIME=2000
        - ZOOKEEPER_SYNC_LIMIT=2
        - ZOOKEEPER_SERVER_ID=1
        - ZOOKEEPER_INIT_LIMIT=5
        - ZOOKEEPER_SERVERS="zookeeper:2888:3888"
        - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=INFO
        - ZOOKEEPER_LOG4J_LOGGERS=org.apache.zookeeper.server.quorum=INFO,org.apache.zookeeper.server=INFO"
        - ZOOKEEPER_LOG_DIR=/var/lib/zookeeper/log
        - ZOOKEEPER_DATA_DIR=/var/lib/zookeeper/data