logging:
  level:
    org.springframework.cloud.contract: debug
    org.testcontainers: FATAL
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
#        spring.json.add.type.headers: false